# Generated by Django 3.2 on 2023-08-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='net_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='net_income',
            field=models.IntegerField(default=0),
        ),
    ]
